--도서의 가격(Book 테이블)과 판매가격(Orders 테이블)의 차이가 가장 많은 주문

SELECT *
FROM (
    SELECT O.ORDERID, B.BOOKNAME, B.PRICE, O.SALEPRICE, (B.PRICE - O.SALEPRICE) AS PRICE_DIFF
    FROM ORDERS O
    JOIN BOOK B ON O.BOOKID = B.BOOKID
    ORDER BY PRICE_DIFF DESC
)
FETCH FIRST 1 ROWS ONLY
