CREATE OR REPLACE PROCEDURE InsertBook(
    myBookID IN NUMBER,
    myBookName IN VARCHAR2,
    myPublisher IN VARCHAR2,
    myPrice IN NUMBER)
AS
BEGIN
    INSERT INTO Book(BOOKID,BOOKNAME, PUBLISHER, PRICE)
        VALUES(MYBOOKID,MYBOOKNAME,MYPUBLISHER,MYPRICE);
END;
/

EXEC InsertBook(13,'스포츠과학','마당과학서적',25000);
SELECT * FROM Book;