//사용자 생성
CREATE USER MDGUEST IDENTIFIED BY MDGUEST
DEFAULT TABLESPACE USERS;

//사용자 삭제
DROP USER MDGUEST CASCADE;

//GRANT 권한 부여
GRANT SELECT ON BOOK TO MDGUEST;
GRANT SELECT, UPDATE ON CUSTOMER TO MDGUEST WITH GRANT OPTION;

//REVOKE 권한 회수
REVOKE SELECT ON BOOK FROM MDGUEST;




//MDGUEST2에게 BOOK 테이블 SELECT 권한 주기
GRANT SELECT ON BOOK TO MDGUEST2;

//MDGUEST에게 권한 부여 후 MDGUEST2에게 권한 다시 부여하기
GRANT SELECT ON BOOK TO MDGUEST WITH GRANT OPTION;
GRANT SELECT ON BOOK TO MDGUEST2;

//권한 회수 mdguest2도 함께 회수됨
REVOKE SELECT ON BOOK FROM MDGUEST;